"""empty message

Revision ID: 0dbf4ab275ef
Revises: 9d0a85d20556
Create Date: 2022-04-20 09:51:42.860772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbf4ab275ef'
down_revision = '9d0a85d20556'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel', sa.Column('category_name', sa.String(length='category.name'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel', 'category_name')
    # ### end Alembic commands ###
