"""empty message

Revision ID: 436c73c7d7b3
Revises: b684e6dc244d
Create Date: 2022-03-27 12:49:13.974472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '436c73c7d7b3'
down_revision = 'b684e6dc244d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_subcategory_id_fkey', 'activity', type_='foreignkey')
    op.create_foreign_key(None, 'activity', 'travel', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.create_foreign_key('activity_subcategory_id_fkey', 'activity', 'travel', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###
