"""empty message

Revision ID: 612ae42f98d6
Revises: 8ecc2afcdb58
Create Date: 2022-03-27 12:40:43.898086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612ae42f98d6'
down_revision = '8ecc2afcdb58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_subcategory_id_fkey', 'activity', type_='foreignkey')
    op.drop_constraint('activity_category_id_fkey', 'activity', type_='foreignkey')
    op.drop_constraint('activity_travel_id_fkey', 'activity', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('activity_travel_id_fkey', 'activity', 'travel', ['travel_id'], ['id'])
    op.create_foreign_key('activity_category_id_fkey', 'activity', 'travel', ['category_id'], ['id'])
    op.create_foreign_key('activity_subcategory_id_fkey', 'activity', 'travel', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###
