"""empty message

Revision ID: 8926c9039b52
Revises: 612ae42f98d6
Create Date: 2022-03-27 12:43:43.700321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8926c9039b52'
down_revision = '612ae42f98d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'activity', 'travel', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    # ### end Alembic commands ###
