"""empty message

Revision ID: 8ecc2afcdb58
Revises: e6f65407a770
Create Date: 2022-03-27 12:33:08.639717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ecc2afcdb58'
down_revision = 'e6f65407a770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('travel_user_id_fkey', 'travel', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('travel_user_id_fkey', 'travel', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
