"""empty message

Revision ID: ad74b95ae1c3
Revises: f66952162b0d
Create Date: 2022-03-27 12:55:57.782324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad74b95ae1c3'
down_revision = 'f66952162b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('activity_category_id_fkey', 'activity', type_='foreignkey')
    op.alter_column('subcategory', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('subcategory_category_id_fkey', 'subcategory', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('subcategory_category_id_fkey', 'subcategory', 'travel', ['category_id'], ['id'])
    op.alter_column('subcategory', 'category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key('activity_category_id_fkey', 'activity', 'travel', ['category_id'], ['id'])
    op.alter_column('activity', 'subcategory_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
