"""empty message

Revision ID: b684e6dc244d
Revises: 8926c9039b52
Create Date: 2022-03-27 12:47:17.830633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b684e6dc244d'
down_revision = '8926c9039b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('activity_category_id_fkey', 'activity', type_='foreignkey')
    op.create_foreign_key(None, 'activity', 'travel', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity', type_='foreignkey')
    op.create_foreign_key('activity_category_id_fkey', 'activity', 'travel', ['category_id'], ['id'])
    # ### end Alembic commands ###
