"""empty message

Revision ID: ff4325ac22cb
Revises: 8fe61476879d
Create Date: 2022-04-25 12:30:18.775438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4325ac22cb'
down_revision = '8fe61476879d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travel', sa.Column('media', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('travel', 'media')
    # ### end Alembic commands ###
